---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: HTTPRoute
      name: subdomain-color-route
    patch: |-
      - op: add
        path: /spec/hostnames/-
        value: "red.dudo.dev"
      - op: add
        path: /spec/hostnames/-
        value: "orange.dudo.dev"
      - op: add
        path: /spec/hostnames/-
        value: "yellow.dudo.dev"
      - op: add
        path: /spec/hostnames/-
        value: "green.dudo.dev"
      - op: add
        path: /spec/hostnames/-
        value: "blue.dudo.dev"
      - op: add
        path: /spec/hostnames/-
        value: "indigo.dudo.dev"
      - op: add
        path: /spec/hostnames/-
        value: "violet.dudo.dev"
      - op: add
        path: /spec/hostnames/-
        value: "black.dudo.dev"
      - op: add
        path: /spec/hostnames/-
        value: "white.dudo.dev"
      - op: add
        path: /spec/hostnames/-
        value: "419fff.dudo.dev"
