---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: HTTPRoute
      name: subdomain-color-route
    patch: |-
      - op: add
        path: /spec/hostnames/-
        value: "red.localhost"
      - op: add
        path: /spec/hostnames/-
        value: "orange.localhost"
      - op: add
        path: /spec/hostnames/-
        value: "yellow.localhost"
      - op: add
        path: /spec/hostnames/-
        value: "green.localhost"
      - op: add
        path: /spec/hostnames/-
        value: "blue.localhost"
      - op: add
        path: /spec/hostnames/-
        value: "indigo.localhost"
      - op: add
        path: /spec/hostnames/-
        value: "violet.localhost"
      - op: add
        path: /spec/hostnames/-
        value: "black.localhost"
